services:
   minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY}
    volumes:
      - minio_data:/data
    user: "${UID}:${GID}"
    command: server /data --console-address ":9001"
    restart: unless-stopped
    networks:
          - laravel-development
   postgres:
    image: postgres:18.1-alpine3.23
    container_name: postgres-docker
    environment:
      - POSTGRES_DB=${DB_DATABASE:-distrozone}
      - POSTGRES_USER=${DB_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-root}
    networks:
      - laravel-development
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  
networks:
  laravel-development:
    
volumes:
  minio_data:
  postgres:
    